DROP SEQUENCE DADOS_SEQUENCE;
DROP TRIGGER TR_INSERT_ID_DADOS;
DROP TABLE DADOS;

CREATE TABLE DADOS (
    ID INTEGER PRIMARY KEY NOT NULL,
    NUTRIENTES VARCHAR(2000) NOT NULL,
    UMIDADE NUMERIC NOT NULL,
    PH NUMERIC NOT NULL,
    SALINIDADE NUMERIC NOT NULL,
    ACOES VARCHAR(2000) NOT NULL,
    SUGESTOES VARCHAR(2000) NOT NULL,
    AUMENTO_PREVISTO NUMERIC NOT NULL,
    USUARIO VARCHAR(200) NOT NULL
);

CREATE SEQUENCE DADOS_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TR_INSERT_ID_DADOS
BEFORE INSERT ON DADOS FOR EACH ROW
BEGIN
 
SELECT DADOS_SEQUENCE.NEXTVAL
INTO :NEW.id
FROM DUAL;
END;
/

COMMIT;